server:
  port: 8080

spring:
  application:
    name: wisercat-backend
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:postgresql://localhost:5032/backend
    username: backend
    password: backend
  flyway:
    enabled: true
    locations: 'classpath:db/migration,classpath:/db/testdata'
    placeholder-replacement: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none

wisercat-backend:
  security:
    cors:
      allowed-origins: http://localhost:5173